### ISSUE TITLE
cannot import name 'parse_queries' from 'data_lineage.parser'

### ISSUE THREAD

**Issue by yohei1126** [tokern/data-lineage#33]
Hi, I am trying to parse query history from Snowflake on Jupyter notebook.

data lineage version 0.3.0

```
!pip install snowflake-connector-python[secure-local-storage,pandas] data-lineage

import datetime
end_time = datetime.datetime.now()
start_time = end_time - datetime.timedelta(days=7)

query = f"""
SELECT query_text
FROM table(information_schema.query_history(
    end_time_range_start=>to_timestamp_ltz('{start_time.isoformat()}'),
    end_time_range_end=>to_timestamp_ltz('{end_time.isoformat()}')));
"""

cursors = conn.execute_string(
    sql_text=query
)

queries = []
for cursor in cursors:
  for row in cursor:
    print(row[0])
    queries.append(row[0])

from data_lineage.parser import parse_queries, visit_dml_queries

# Parse all queries
parsed = parse_queries(queries)

# Visit the parse trees to extract source and target queries
visited = visit_dml_queries(catalog, parsed)

# Create a graph and visualize it

from data_lineage.parser import create_graph
graph = create_graph(catalog, visited)

import plotly
plotly.offline.iplot(graph.fig())
````

Then I got this error. Would you help me find the root cause?

```
---------------------------------------------------------------------------
ImportError                               Traceback (most recent call last)
<ipython-input-33-151c67ea977c> in <module>
----> 1 from data_lineage.parser import parse_queries, visit_dml_queries
      2 
      3 # Parse all queries
      4 parsed = parse_queries(queries)
      5 

ImportError: cannot import name 'parse_queries' from 'data_lineage.parser' (/opt/conda/lib/python3.8/site-packages/data_lineage/parser/__init__.py)
```

**Comment by vrajat** [comment]
Hi,
Thanks for trying out data-lineage and sorry for the rough edges in the package. I am assuming you've picked up code from the examples in the doc. I hadn't released a new version of the application and I have just released v0.5.1. Please install the latest package by running `pip install -U data-lineage` . This should solve the immediate problem of missing imports.

However, I do see a couple of gaps in your script. You have to setup a postgres database for the catalog. The easiest way to setup a postgres database on your laptop using docker. Let me know if you need help.

**Comment by yohei1126** [comment]
thanks I am using snowflake

**Comment by yohei1126** [comment]
still failing

```
import datetime
end_time = datetime.datetime.now()
start_time = end_time - datetime.timedelta(days=7)

query = f"""
SELECT query_text
FROM table(information_schema.query_history(
    end_time_range_start=>to_timestamp_ltz('{start_time.isoformat()}'),
    end_time_range_end=>to_timestamp_ltz('{end_time.isoformat()}')));
"""

cursors = conn.execute_string(
    sql_text=query
)

queries = []
for cursor in cursors:
  for row in cursor:
    print(f"{row[0]}")
    queries.append(row[0])
```

This shows query history as follows.

```
SELECT query_text
FROM table(information_schema.query_history(
    end_time_range_start=>to_timestamp_ltz('2021-04-25T13:46:32.544154'),
    end_time_range_end=>to_timestamp_ltz('2021-05-02T13:46:32.544154')));
SELECT query_text
FROM table(information_schema.query_history(
    end_time_range_start=>to_timestamp_ltz('2021-04-25T13:46:20.237862'),
    end_time_range_end=>to_timestamp_ltz('2021-05-02T13:46:20.237862')));
SELECT query_text
FROM table(information_schema.query_history(
    end_time_range_start=>to_timestamp_ltz('2021-04-25T13:45:18.371513'),
    end_time_range_end=>to_timestamp_ltz('2021-05-02T13:45:18.371513')));
SELECT query_text
FROM table(information_schema.query_history(
    end_time_range_start=>to_timestamp_ltz('2021-04-25T13:44:27.187499'),
    end_time_range_end=>to_timestamp_ltz('2021-05-02T13:44:27.187499')));
SELECT query_text
FROM table(information_schema.query_history(
    end_time_range_start=>to_timestamp_ltz('2021-04-24T07:25:55.213431'),
    end_time_range_end=>to_timestamp_ltz('2021-05-01T07:25:55.213431')));
SELECT query_text
FROM table(information_schema.query_history(
    end_time_range_start=>to_timestamp_ltz('2021-04-24T07:25:23.433387'),
    end_time_range_end=>to_timestamp_ltz('2021-05-01T07:25:23.433387')));
SELECT query_text
FROM table(information_schema.query_history(
    end_time_range_start=>to_timestamp_ltz('2021-04-24T07:10:29.311609'),
    end_time_range_end=>to_timestamp_ltz('2021-05-01T07:10:29.311609')));
SELECT query_text
FROM table(information_schema.query_history(
    end_time_range_start=>to_timestamp_ltz('2021-04-24T07:03:48.882660'),
    end_time_range_end=>to_timestamp_ltz('2021-05-01T07:03:48.882660')));
SELECT query_text
FROM table(information_schema.query_history(
    end_time_range_start=>to_timestamp_ltz('2021-04-24T07:02:13.962780'),
    end_time_range_end=>to_timestamp_ltz('2021-05-01T07:02:13.962780')));
SELECT query_text
FROM table(information_schema.query_history(
    end_time_range_start=>to_timestamp_ltz('2021-04-24T07:02:03.205936'),
    end_time_range_end=>to_timestamp_ltz('2021-05-01T07:02:03.205936')));
SELECT query_text
FROM table(information_schema.query_history(
    end_time_range_start=>to_timestamp_ltz('2021-04-01 00:00:00 +0800'),
    end_time_range_end=>to_timestamp_ltz('2021-05-01 00:00:00 +0800')));
SELECT query_text
FROM table(information_schema.query_history(
    end_time_range_start=>to_timestamp_ltz('2021-04-30 23:59:59 +0800'),
    end_time_range_end=>to_timestamp_ltz('2021-04-26 00:00:00 +0800')));
SELECT query_text
FROM table(information_schema.query_history(
    end_time_range_start=>to_timestamp_ltz('2021-04-30 23:59:59 +0800'),
    end_time_range_end=>to_timestamp_ltz('2021-04-6 00:00:00 +0800')));
put file:☺☺☺☺☺☺☺☺☺☺☺☺☺☺☺☺☺☺☺☺☺☺☺☺☺☺☺☺.csv @-/staged;
PUT file:☺☺☺☺☺☺☺☺☺☺☺☺☺☺☺☺☺☺☺☺☺☺☺☺☺☺☺☺.csv @-/staged;
COPY INTO tmp1
FROM @ANALYTICS_CUSTOM_PH/tmp1.csv
FILE_FORMAT = (
  TYPE = CSV  SKIP_HEADER = 1
);
LIST @ANALYTICS_CUSTOM_PH;
LIST @ANALYTICS_CUSTOM;
CREATE OR REPLACE TABLE tmp1(a INT, b STRING);
SHOW GRANTS TO USER identifier('"YOHEI"');
SELECT * FROM identifier('"SINGLIFE"."ANALYTICS_CUSTOM"."TMP1"') LIMIT 100;
COPY INTO tmp1
FROM @ANALYTICS_CUSTOM/tmp1.csv
FILE_FORMAT = (
  TYPE = CSV  SKIP_HEADER = 1
);
COPY INTO tmp1
FROM @ANALYTICS_CUSTOM/tmp1.csv
HEADER;
COPY INTO tmp1
FROM @ANALYTICS_CUSTOM/tmp1.csv
HEADER = TRUE;
COPY INTO tmp1
FROM @ANALYTICS_CUSTOM/tmp1.csv
FILE_FORMAT = (TYPE = CSV)
HEADER = TRUE;
COPY INTO tmp1
FROM @ANALYTICS_CUSTOM/tmp1.csv
FILE_FORMAT = (TYPE = CSV HEADER = TRUE);
COPY INTO tmp1
FROM @ANALYTICS_CUSTOM/tmp1.csv;
LIST @ANALYTICS_CUSTOM;
SHOW STAGES LIKE 'ANALYTICS_CUSTOM_PH' IN SCHEMA "SINGLIFE"."ANALYTICS_CUSTOM_PH"
SHOW STAGES LIKE 'ANALYTICS_CUSTOM' IN SCHEMA "SINGLIFE"."ANALYTICS_CUSTOM"
DESCRIBE STAGE "SINGLIFE"."ANALYTICS_CUSTOM"."ANALYTICS_CUSTOM"
DESCRIBE STAGE "SINGLIFE"."ANALYTICS_CUSTOM_PH"."ANALYTICS_CUSTOM_PH"
ALTER STAGE "SINGLIFE"."ANALYTICS_CUSTOM_PH"."ANALYTICS_CUSTOM_PH" SET URL = 's3://singlife-data-pf-sandbox-dev/analytics_custom_ph/'
ALTER STAGE "SINGLIFE"."ANALYTICS_CUSTOM"."ANALYTICS_CUSTOM" SET URL = 's3://singlife-data-pf-sandbox-dev/analytics_custom/'
SHOW GRANTS OF ROLE "DATA_ENGINEERING_ADVANCED"
SHOW GRANTS OF ROLE "DATA_ANALYST_ADVANCED_PH"
SHOW GRANTS OF ROLE "DATA_ANALYST_BASE_PH"
SHOW GRANTS OF ROLE "DATA_ANALYST_ADVANCED"
SHOW GRANTS OF ROLE "SNOWPIPE"
SHOW GRANTS OF ROLE "DEPLOY_ADMIN"
SHOW GRANTS ON SCHEMA "SINGLIFE"."LANDING_REALTIME"
SHOW GRANTS ON SCHEMA "SINGLIFE"."LANDING_REALTIME"
SHOW GRANTS ON SCHEMA "SINGLIFE"."LANDING_REALTIME"
SHOW GRANTS ON SCHEMA "SINGLIFE"."LANDING_REALTIME"
SHOW GRANTS ON SCHEMA "SINGLIFE"."LANDING_REALTIME"
SHOW FUTURE GRANTS IN SCHEMA "SINGLIFE"."LANDING_REALTIME"
SHOW GRANTS ON SCHEMA "SINGLIFE"."LANDING_REALTIME"
SHOW GRANTS ON SCHEMA "SINGLIFE"."LANDING_REALTIME"
SHOW GRANTS ON SCHEMA "SINGLIFE"."LANDING_REALTIME"
SHOW GRANTS ON SCHEMA "SINGLIFE"."LANDING_REALTIME"
SHOW FUTURE GRANTS IN SCHEMA "SINGLIFE"."LANDING_REALTIME"
SHOW GRANTS ON SCHEMA "SINGLIFE"."LANDING_REALTIME"
SHOW FUTURE GRANTS IN SCHEMA "SINGLIFE"."LANDING_REALTIME"
SHOW GRANTS ON SCHEMA "SINGLIFE"."LANDING_REALTIME"
SHOW FUTURE GRANTS IN SCHEMA "SINGLIFE"."LANDING_REALTIME"
SHOW GRANTS ON SCHEMA "SINGLIFE"."LANDING_REALTIME"
SHOW GRANTS ON SCHEMA "SINGLIFE"."ANALYTICS_PH"
SHOW GRANTS ON SCHEMA "SINGLIFE"."LANDING_REALTIME"
SHOW FUTURE GRANTS IN SCHEMA "SINGLIFE"."LANDING_REALTIME"
SHOW GRANTS ON SCHEMA "SINGLIFE"."ANALYTICS_PH"
SHOW GRANTS ON SCHEMA "SINGLIFE"."ANALYTICS_PH"
SHOW GRANTS ON SCHEMA "SINGLIFE"."ANALYTICS_PH"
SHOW GRANTS ON SCHEMA "SINGLIFE"."LANDING_REALTIME"
SHOW FUTURE GRANTS IN SCHEMA "SINGLIFE"."ANALYTICS"
SHOW GRANTS ON SCHEMA "SINGLIFE"."ANALYTICS_PH"
SHOW FUTURE GRANTS IN SCHEMA "SINGLIFE"."ANALYTICS_PH"
SHOW GRANTS ON SCHEMA "SINGLIFE"."ANALYTICS_PH"
SHOW FUTURE GRANTS IN SCHEMA "SINGLIFE"."ANALYTICS_PH"
SHOW GRANTS ON SCHEMA "SINGLIFE"."ANALYTICS_PH"
SHOW GRANTS ON SCHEMA "SINGLIFE"."ANALYTICS"
SHOW GRANTS ON SCHEMA "SINGLIFE"."ANALYTICS"
SHOW GRANTS ON SCHEMA "SINGLIFE"."ANALYTICS"
SHOW GRANTS ON SCHEMA "SINGLIFE"."ANALYTICS_PH"
SHOW GRANTS ON SCHEMA "SINGLIFE"."ANALYTICS"
SHOW GRANTS ON SCHEMA "SINGLIFE"."ANALYTICS"
SHOW FUTURE GRANTS IN SCHEMA "SINGLIFE"."ANALYTICS"
SHOW FUTURE GRANTS IN SCHEMA "SINGLIFE"."ANALYTICS_PH"
SHOW GRANTS ON SCHEMA "SINGLIFE"."ANALYTICS"
SHOW GRANTS ON SCHEMA "SINGLIFE"."ANALYTICS"
SHOW GRANTS ON SCHEMA "SINGLIFE"."ANALYTICS"
SHOW GRANTS ON SCHEMA "SINGLIFE"."ANALYTICS_PH"
SHOW FUTURE GRANTS IN SCHEMA "SINGLIFE"."ANALYTICS_PH"
SHOW GRANTS ON SCHEMA "SINGLIFE"."ANALYTICS_PH"
SHOW FUTURE GRANTS IN SCHEMA "SINGLIFE"."ANALYTICS"
SHOW GRANTS ON SCHEMA "SINGLIFE"."ANALYTICS"
SHOW GRANTS ON SCHEMA "SINGLIFE"."ANALYTICS_PH"
SHOW FUTURE GRANTS IN SCHEMA "SINGLIFE"."ANALYTICS_PH"
SHOW GRANTS ON SCHEMA "SINGLIFE"."ANALYTICS_PH"
SHOW GRANTS ON SCHEMA "SINGLIFE"."ANALYTICS"
SHOW GRANTS ON SCHEMA "SINGLIFE"."ANALYTICS"
SHOW GRANTS ON SCHEMA "SINGLIFE"."ANALYTICS_PH"
SHOW GRANTS ON SCHEMA "SINGLIFE"."ANALYTICS_PH"
SHOW GRANTS ON SCHEMA "SINGLIFE"."ANALYTICS"
SHOW GRANTS ON SCHEMA "SINGLIFE"."ANALYTICS_CUSTOM_PH"
SHOW GRANTS ON SCHEMA "SINGLIFE"."ANALYTICS"
SHOW GRANTS ON SCHEMA "SINGLIFE"."ANALYTICS_CUSTOM_PH"
SHOW FUTURE GRANTS IN SCHEMA "SINGLIFE"."ANALYTICS"
SHOW FUTURE GRANTS IN SCHEMA "SINGLIFE"."ANALYTICS"
SHOW GRANTS ON SCHEMA "SINGLIFE"."ANALYTICS_CUSTOM_PH"
SHOW GRANTS ON SCHEMA "SINGLIFE"."ANALYTICS_CUSTOM_PH"
```

```
from data_lineage.parser import parse_queries, visit_dml_queries

# Parse all queries
parsed = parse_queries(queries)

# Visit the parse trees to extract source and target queries
visited = visit_dml_queries(catalog, parsed)

# Create a graph and visualize it

from data_lineage.parser import create_graph
graph = create_graph(catalog, visited)

import plotly
plotly.offline.iplot(graph.fig())
```

Got this error.

```
---------------------------------------------------------------------------
ParseError                                Traceback (most recent call last)
<ipython-input-12-151c67ea977c> in <module>
      2 
      3 # Parse all queries
----> 4 parsed = parse_queries(queries)
      5 
      6 # Visit the parse trees to extract source and target queries

/opt/conda/lib/python3.8/site-packages/data_lineage/parser/__init__.py in parse_queries(queries)
     17 
     18 def parse_queries(queries: List[str]) -> List[Parsed]:
---> 19     return [parse(query) for query in queries]
     20 
     21 

/opt/conda/lib/python3.8/site-packages/data_lineage/parser/__init__.py in <listcomp>(.0)
     17 
     18 def parse_queries(queries: List[str]) -> List[Parsed]:
---> 19     return [parse(query) for query in queries]
     20 
     21 

/opt/conda/lib/python3.8/site-packages/data_lineage/parser/node.py in parse(sql, name)
    319     if name is None:
    320         name = str(hash(sql))
--> 321     node = AcceptingNode(parse_sql(sql))
    322 
    323     return Parsed(name, node)

pglast/parser.pyx in pglast.parser.parse_sql()

ParseError: syntax error at or near "table", at location 24

```

**Comment by yohei1126** [comment]
Any instruction for Snowflake?
